replicaCount: 2

image:
  repository: roarceus/trading-service-k8s
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080

env:
  DB_HOST: "trading-rds.ca96862amkmy.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "sohan"
  DB_PASSWORD: "password"
  DB_NAME: "trading_db"

resources: {}

istio:
  enabled: true
