apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: trading-service-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trading-service
spec:
  hosts:
    - "*"
  gateways:
    - trading-service-gateway
  http:
    - route:
        - destination:
            host: {{ include "trading-service.fullname" . }}
            port:
              number: 8080
