name: Build Docker Image on PR

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/trading-service-k8s

on:
  pull_request:
    branches: [ main ]

jobs:
  push-image:
    name: "Build Docker Image on PR"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ${{ env.DOCKER_IMAGE }}:pr-${{ github.sha }}
