name: Build and Deploy

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/trading-service-k8s

on:
  push:
    branches: [ main ]

jobs:
  build-image:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}