name: "Terraform Validate"

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: "Terraform Format and Validate"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7

      - name: "Terraform Init"
        run: |
          if [ -d "k8s" ]; then
            echo "Initializing Terraform in k8s/"
            terraform -chdir=k8s init -backend=false
          fi

      - name: "Terraform Format Check"
        run: |
          for dir in k8s k8s/eks k8s/rds; do
            if [ -d "$dir" ]; then
              echo "Checking Terraform format in $dir"
              terraform -chdir=$dir fmt -check
            fi
          done

      - name: "Terraform Validate"
        run: |
          if [ -d "k8s" ]; then
            echo "Validating Terraform in k8s/"
            terraform -chdir=k8s validate
          fi
